//package org.orm.criteria;
//
//import static org.junit.Assert.assertEquals;
//import static org.orm.criteria.aggregate.Aggregate.field;
//import static org.orm.criteria.aggregate.Aggregate.*;
//import static org.orm.criteria.aggregate.Aggregate.nul;
//import static org.orm.criteria.order.Order.asc;
//import static org.orm.criteria.restriction.Restriction.*;
//
//import java.util.List;
//
//import org.junit.After;
//import org.junit.Before;
//import org.junit.Test;
//import org.orm.criteria.aggregate.Aggregator;
//import org.orm.mapper.DataMapper;
//import org.orm.mapper.EntityMapper;
//import org.orm.query.QueryObject;
//import org.orm.record.Entity;
//import org.orm.session.SessionFactory;
//import org.orm.test.EntityTest2;
//
//public class GroupByTest {
//
//	static {
//		new EntityTest2();
//	}
//
//	@Before
//	public void before() {
//		SessionFactory.getSession().open();
//
//		DataMapper.executeDDLIgnoringErrors("DROP TABLE A");
//
//		DataMapper.executeDDL(
//		/**/"CREATE TABLE A(" +
//		/**/"ID_A INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY," +
//		/**/"NAME VARCHAR(10)," +
//		/**/"CITY VARCHAR(10)," +
//		/**/"AGE INTEGER" +
//		/**/")"
//		/**/);
//		SessionFactory.getSession().commit();
//	}
//
//	@After
//	public void after() {
//		try {
//			SessionFactory.getSession().open();
//			DataMapper.executeDDLIgnoringErrors("DROP TABLE A");
//			SessionFactory.getSession().commit();
//		} catch (final Exception e) {
//			e.printStackTrace();
//		}
//	}
//
//	@Test
//	public void testA() throws Exception {
//
//		SessionFactory.getSession().open();
//
//		DataMapper.executeDDL("INSERT INTO A (ID_A,NAME,CITY,AGE) VALUES (1,'MH','SBD',29)");
//		DataMapper.executeDDL("INSERT INTO A (ID_A,NAME,CITY,AGE) VALUES (2,'RH','BCN',23)");
//		DataMapper.executeDDL("INSERT INTO A (ID_A,NAME,CITY,AGE) VALUES (3,'MH','BCN',22)");
//		DataMapper.executeDDL("INSERT INTO A (ID_A,NAME,CITY,AGE) VALUES (4,'RO','VIC',27)");
//		DataMapper.executeDDL("INSERT INTO A (ID_A,NAME,CITY,AGE) VALUES (5,'CA','LNZ',52)");
//
//		try {
//
//			final Entity r1 = DataMapper.queryUnique(new EntityMapper(A.class),
//			/**/new QueryObject()
//			/**/.append(" SELECT NULL AS ID_A, NULL AS NAME, NULL AS CITY, MAX(AGE) AS AGE")
//			/**/.append(" FROM A")
//			/**/.append(" GROUP BY CITY")
//			/**/.append(" ")
//			/**/.append(" ")
//			/**/);
//
//			assertEquals("[ID_A=null, NAME=null, CITY=null, AGE=52]", r1.toString());
//
//			final List<Entity> r2 = DataMapper.query(new EntityMapper(A.class),
//			/**/new QueryObject()
//			/**/.append(" SELECT NULL AS ID_A, NULL AS NAME, CITY, MAX(AGE) AS AGE")
//			/**/.append(" FROM A")
//			/**/.append(" GROUP BY CITY")
//			/**/.append(" ")
//			/**/.append(" ")
//			/**/);
//
//			assertEquals(
//			/**/"[[ID_A=null, NAME=null, CITY=SBD, AGE=29], " +
//			/**/"[ID_A=null, NAME=null, CITY=BCN, AGE=23], " +
//			/**/"[ID_A=null, NAME=null, CITY=VIC, AGE=27], " +
//			/**/"[ID_A=null, NAME=null, CITY=LNZ, AGE=52]]"
//			/**/, r2.toString());
//
//			final List<Entity> r3 = DataMapper.query(new EntityMapper(A.class),
//			/**/new QueryObject()
//			/**/.append(" SELECT NULL AS ID_A, MAX(NAME) AS NAME, CITY, MAX(AGE) AS AGE")
//			/**/.append(" FROM A")
//			/**/.append(" GROUP BY CITY")
//			/**/.append(" ")
//			/**/.append(" ")
//			/**/);
//
//			assertEquals(
//			/**/"[[ID_A=null, NAME=MH, CITY=SBD, AGE=29], " +
//			/**/"[ID_A=null, NAME=RH, CITY=BCN, AGE=23], " +
//			/**/"[ID_A=null, NAME=RO, CITY=VIC, AGE=27], " +
//			/**/"[ID_A=null, NAME=CA, CITY=LNZ, AGE=52]]"
//			/**/, r3.toString());
//
//			final List<A> vellsPerCity =
//			/**/Criteria.select(A.class, nul(A.id), max(A.name, "NAME"), field(A.city), max(A.age, "AGE"))
//			/**/.groupBy(A.city)
//			/**/.get();
//
//			assertEquals(
//			/**/"[[ID_A=null, NAME=MH, CITY=SBD, AGE=29], " +
//			/**/"[ID_A=null, NAME=RH, CITY=BCN, AGE=23], " +
//			/**/"[ID_A=null, NAME=RO, CITY=VIC, AGE=27], " +
//			/**/"[ID_A=null, NAME=CA, CITY=LNZ, AGE=52]]"
//			/**/, vellsPerCity.toString());
//
//			final List<A> vellsPerCity2 =
//			/**/Criteria.select(A.class, nul(A.id), max(A.name, "NAME"), field(A.city), max(A.age, "AGE"))
//			/**/.groupBy(A.city)
//			/**/.having(ne(A.city, "LNZ"))
//			/**/.orderBy(asc(A.age))
//			/**/.get();
//
//			assertEquals(
//			/**/"[[ID_A=null, NAME=RH, CITY=BCN, AGE=23], " +
//			/**/"[ID_A=null, NAME=RO, CITY=VIC, AGE=27], " +
//			/**/"[ID_A=null, NAME=MH, CITY=SBD, AGE=29]]"
//			/**/, vellsPerCity2.toString());
//
//			// TODO i com aggregar?
//			// Long n = Criteria.select(A.class,
//			// Aggregator.countAll(A.age)).getUnique();
//
//		} catch (final Exception e) {
//			e.printStackTrace();
//			throw e;
//		} finally {
//			SessionFactory.getSession().rollback();
//		}
//	}
//
// }
