package org.orm.test;

import static org.junit.Assert.assertEquals;

import java.util.Arrays;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.orm.criteria.Criteria;
import org.orm.mapper.DataMapper;
import org.orm.session.SessionFactory;
import org.orm.test.ent.Dog;
import org.orm.test.ent.Rabbit;

public class SaveTest {

	static {
		new EntityTest2();
	}

	@Before
	public void before() {
		SessionFactory.getSession().open();

		DataMapper.executeDDLIgnoringErrors("DROP TABLE DOG");
		DataMapper.executeDDLIgnoringErrors("DROP TABLE RABBIT");

		DataMapper.executeDDL(
		/**/"CREATE TABLE RABBIT (" +
		/**/"ID_RABBIT INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY," +
		/**/"NAME VARCHAR(20)," +
		/**/"AGE INTEGER," +
		/**/"NUM_DOG INTEGER)"
		/**/);
		DataMapper.executeDDL(
		/**/"CREATE TABLE DOG (" +
		/**/"ID_DOG INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY," +
		/**/"NAME VARCHAR(20)," +
		/**/"AGE INTEGER)"
		/**/);
		SessionFactory.getSession().commit();
	}

	@After
	public void after() {
		// TODO embolcallar amb trys els afters i chupant l'excepció. Si peta el
		// test, fa petar això i l'excepció original es perd
		try {
			SessionFactory.getSession().open();
			DataMapper.executeDDL("DROP TABLE RABBIT");
			DataMapper.executeDDL("DROP TABLE DOG");
			SessionFactory.getSession().commit();
		} catch (final Exception e) {
			e.printStackTrace();
		}
	}

	@Test
	public void testInsertDogInsertRabbits() {

		SessionFactory.getSession().open();

		try {

			final Dog d = new Dog(null, "din", 10);
			d.setRabbits(Arrays.asList(new Rabbit(null, "corneju1", 3), new Rabbit(null, "corneju2", 4)));

			d.store();
			System.out.println("====================================");

			SessionFactory.getSession().getIdCache().clear();

			final Dog d2 = Criteria.selectById(Dog.class, 100);
			assertEquals("[ID_DOG=100, NAME=din, AGE=10, [...]]", d2.toString());
			d2.getRabbits();
			assertEquals(
			/**/"[ID_DOG=100, NAME=din, AGE=10, " +
			/**/"[[ID_RABBIT=100, NAME=corneju1, AGE=3, NUM_DOG=100=>[...]], " +
			/**/"[ID_RABBIT=101, NAME=corneju2, AGE=4, NUM_DOG=100=>[...]]]]",
			/**/d2.toString());

		} finally {
			SessionFactory.getSession().rollback();
		}
	}

	@Test
	public void testInsertRabbitInsertDog() {

		SessionFactory.getSession().open();

		try {

			final Rabbit r = new Rabbit(null, "corneju", 6);
			r.setDog(new Dog(null, "din", 8));
			r.store();
			assertEquals(
					"[ID_RABBIT=100, NAME=corneju, AGE=6, NUM_DOG=100=>[ID_DOG=100, NAME=din, AGE=8, [...]]]",
					r.toString());

			SessionFactory.getSession().getIdCache().clear();

			final Rabbit r2 = Criteria.selectById(Rabbit.class, 100);
			assertEquals("[ID_RABBIT=100, NAME=corneju, AGE=6, NUM_DOG=100=>[...]]", r2.toString());
			r2.getDog();
			assertEquals(
					"[ID_RABBIT=100, NAME=corneju, AGE=6, NUM_DOG=100=>[ID_DOG=100, NAME=din, AGE=8, [...]]]",
					r2.toString());

		} finally {
			SessionFactory.getSession().rollback();
		}
	}

}
