package org.orm.antipojo;

import static org.junit.Assert.assertEquals;
import static org.orm.criteria.Criteria.query;
import static org.orm.criteria.Criteria.selectBy;
import static org.orm.criteria.restriction.Restriction.eq;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.orm.criteria.Criteria;
import org.orm.datasource.HsqldbDataSourceFactory;
import org.orm.mapper.DataMapper;
import org.orm.record.field.regular.primitive.FLong;
import org.orm.session.SessionFactory;
import org.orm.test.EntityTest2;

public class NoPojoTest {

	static {
		new EntityTest2();
		SessionFactory.configDataSource(new HsqldbDataSourceFactory().getDataSource());
	}

	@Test
	public void test() {

		SessionFactory.getSession().open();

		try {
			DataMapper.executeDDL("INSERT INTO CITY (ID_CITY,NAME) VALUES (100,'SBD')");
			DataMapper.sqlStatement("INSERT INTO CITY (ID_CITY,NAME) VALUES (?,?)", 101, "TRS");

			City sbd = selectBy(eq(City.name, "SBD")).uniqueResult(City.class);
			assertEquals("[ID_CITY=100, NAME=SBD]", sbd.toString());

			sbd.set(City.name, "Sabadell");
			sbd.store();

			sbd = Criteria.selectById(City.class, sbd.get(City.id));
			assertEquals("[ID_CITY=100, NAME=Sabadell]", sbd.toString());

			assertEquals("[[ID_CITY=100, NAME=Sabadell], [ID_CITY=101, NAME=TRS]]",
			/**/Criteria.selectAll().list(City.class).toString());

			final long count = query("SELECT COUNT(*) AS VALUE FROM CITY").getColumnValue(new FLong("VALUE"));
			assertEquals(2L, count);

		} finally {
			SessionFactory.getSession().rollback();
		}
	}

	@Before
	public void before() {
		SessionFactory.getSession().open();

		DataMapper.executeDDLIgnoringErrors("DROP TABLE CITY");

		DataMapper.executeDDL(
		/**/"CREATE TABLE CITY (" +
		/**/"   ID_CITY INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY," +
		/**/"   NAME VARCHAR(20)" +
		/**/")"
		/**/);
		SessionFactory.getSession().commit();
	}

	@After
	public void after() {
		SessionFactory.getSession().open();
		DataMapper.executeDDL("DROP TABLE CITY");
		SessionFactory.getSession().commit();
	}

}
