package org.morm.test;

import org.junit.Test;
import org.morm.criteria.impl.OrderBy;
import org.morm.datasource.HsqldbDataSourceFactory;
import org.morm.exception.FrijolesException;
import org.morm.mapper.DataMapper;
import org.morm.session.SessionFactory;

import static org.junit.Assert.*;
import static org.morm.criteria.Criteria.*;

public class M {

	static {
		new SessionFactory().setDataSource(new HsqldbDataSourceFactory().getDataSource());
	}

	@Test
	public void testname() throws Exception {

		{
			SessionFactory.getCurrentSession().beginTransaction();
			DataMapper
					.executeDDL("CREATE TABLE RABBIT (ID_RABBIT INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100) PRIMARY KEY,NAME VARCHAR(20),AGE INTEGER)");
		}
		{
			final Rabbit X = new Rabbit();

			final Rabbit a = new Rabbit(null, "din", 9);
			a.store();

			System.out.println(a);

			try {
				X.loadById(4);
				fail();
			} catch (final FrijolesException e2) {
				// assertEquals("java.lang.RuntimeException: no row produced",
				// e2.getMessage());
			}

			final Rabbit rabbit = X.loadById(100);
			System.out.println(rabbit);

			rabbit.setName("jou");
			rabbit.store();

			System.out.println(X.loadById(100));
			System.out.println(X.loadAll());

			System.out.println(X.loadBy(eq(Rabbit.id, 4)));
			System.out.println(X.loadBy(eq(Rabbit.id, 100)));
			System.out.println(X.loadBy(and(eq(Rabbit.id, 5), eq(Rabbit.name, "jou"))));

			System.out.println(X.
			/**/loadBy(eq(Rabbit.id, 100), orderBy(OrderBy.ASC, Rabbit.name, Rabbit.id))
			/**/);

			System.out.println(X.count(eq(Rabbit.id, 4)));
			System.out.println(X.count(eq(Rabbit.id, 100)));

			rabbit.delete();

			System.out.println(Rabbit.findAll());
			SessionFactory.getCurrentSession().rollback();
		}
		{
			SessionFactory.getCurrentSession().beginTransaction();
			DataMapper.executeDDL("DROP TABLE RABBIT");
			SessionFactory.getCurrentSession().commit();
		}
	}

}
